# Generated by Django 6.0.4 on 2026-05-11 06:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0007_backfill_auth_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], default='present', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='Gym.gym_user')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date', 'member'], name='Gym_attenda_date_a8fdab_idx'), models.Index(fields=['member', 'date'], name='Gym_attenda_member__8df224_idx')],
                'unique_together': {('member', 'date')},
            },
        ),
    ]
