# Generated by Django 6.0.4 on 2026-05-16 23:25

import Gym.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0008_attendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.PositiveIntegerField(help_text='Membership duration in days.', validators=[django.core.validators.MinValueValidator(1)])),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('membership_status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.ImageField(upload_to=Gym.models.payment_proof_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), Gym.models.validate_payment_screenshot_size])),
                ('utr_number', models.CharField(max_length=50, unique=True)),
                ('payment_method', models.CharField(choices=[('upi', 'Manual UPI')], default='upi', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('admin_note', models.TextField(blank=True)),
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_proof', to='Gym.membership')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_proofs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['user', 'created_at'], name='Gym_members_user_id_ff2d7a_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['payment_status', 'membership_status'], name='Gym_members_payment_15a433_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentproof',
            index=models.Index(fields=['payment_status', 'uploaded_at'], name='Gym_payment_payment_67e963_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentproof',
            index=models.Index(fields=['user', 'uploaded_at'], name='Gym_payment_user_id_951607_idx'),
        ),
    ]
